services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NcWerbung\ContaoAiAltTextBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,ContaoManager,NcWerbungContaoAiAltTextBundle.php}'

    # Controllers
    NcWerbung\ContaoAiAltTextBundle\Controller\ProxyController:
        public: true
        arguments:
            $apiUrl: '%nc_werbung_ai_alt_text.api_url%'
            $apiKey: '%nc_werbung_ai_alt_text.api_key%'
            $model: '%nc_werbung_ai_alt_text.model%'

    # Event Listeners
    NcWerbung\ContaoAiAltTextBundle\EventListener\AddBackendAssetsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
